service: sls-go-crud

provider:
  name: aws
  runtime: go1.x
  region: us-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-1:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/apis/create
    events:
      - http:
          path: /dogs
          method: post

  list:
    handler: bin/apis/list
    events:
      - http:
          path: /dogs
          method: get
          
  get:
    handler: bin/apis/get
    events:
      - http:
          path: /dogs/{id}
          method: get
          
  delete:
    handler: bin/apis/delete
    events:
      - http:
          path: /dogs/{id}
          method: delete
          
  update:
    handler: bin/apis/update
    events:
      - http:
          path: /dogs/{id}
          method: put           
